version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    restart: always
    environment:
      - DEBUG=True  # You can add environment variables here if needed

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules  # Avoid overwriting node_modules from the host
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    restart: always

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile  # مسیر Dockerfile برای Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # تنظیمات Nginx
    ports:
      - 80:80  # پورت 80 برای Nginx
    depends_on:
      - frontend  # ابتدا frontend باید بالا بیاید
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
