version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/dev/django/Dockerfile
    container_name: backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    restart: always

  frontend:
    container_name: app
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./app/:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000

volumes:
  pgdata:
