# Generated by Django 5.1.2 on 2024-11-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس (انگلیسی)')),
                ('address_persian', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس (فارسی)')),
                ('address_arabic', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس (عربی)')),
                ('location_link', models.CharField(blank=True, max_length=128, null=True, verbose_name='لینک مکان')),
                ('footer_caption', models.CharField(blank=True, max_length=80, null=True, verbose_name='عنوان فوتر (انگلیسی)')),
                ('footer_caption_persian', models.CharField(blank=True, max_length=80, null=True, verbose_name='عنوان فوتر (فارسی)')),
                ('footer_caption_arabic', models.CharField(blank=True, max_length=80, null=True, verbose_name='عنوان فوتر (عربی)')),
                ('slogan', models.CharField(blank=True, max_length=60, null=True, verbose_name='شعار (انگلیسی)')),
                ('slogan_persian', models.CharField(blank=True, max_length=60, null=True, verbose_name='شعار (فارسی)')),
                ('slogan_arabic', models.CharField(blank=True, max_length=60, null=True, verbose_name='شعار (عربی)')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('activate', models.BooleanField(default=False, verbose_name='فعال\u200cسازی')),
            ],
            options={
                'verbose_name': 'فوتر',
                'verbose_name_plural': 'فوترها',
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر سایت',
                'verbose_name_plural': 'تصاویر سایت',
            },
        ),
        migrations.CreateModel(
            name='SiteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'ویدیو سایت',
                'verbose_name_plural': 'ویدیوهای سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=70, null=True, verbose_name='واتساپ')),
                ('linkedin', models.CharField(blank=True, max_length=70, null=True, verbose_name='لینکدین')),
                ('instagram', models.CharField(blank=True, max_length=70, null=True, verbose_name='اینستاگرام')),
                ('activate', models.BooleanField(default=False, verbose_name='فعال\u200cسازی')),
            ],
            options={
                'verbose_name': 'لینک شبکه اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای شبکه اجتماعی',
            },
        ),
    ]
