# Generated by Django 5.1.2 on 2024-11-23 11:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/extra/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان (انگلیسی)')),
                ('title_persian', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان (فارسی)')),
                ('title_arabic', models.CharField(max_length=100, verbose_name='عنوان (عربی)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='نامک')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان (انگلیسی)')),
                ('title_persian', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان (فارسی)')),
                ('title_arabic', models.CharField(max_length=100, verbose_name='عنوان (عربی)')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='تصویر اصلی')),
                ('caption', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات (انگلیسی)')),
                ('caption_persian', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات (فارسی)')),
                ('caption_arabic', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات (عربی)')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='نامک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
                ('extra_images', models.ManyToManyField(blank=True, related_name='products', to='products.productimage', verbose_name='تصاویر اضافی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
