# Generated by Django 5.1.2 on 2024-11-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email_address', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان (انگلیسی)')),
                ('title_persian', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان (فارسی)')),
                ('title_arabic', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان (عربی)')),
                ('about', models.CharField(blank=True, max_length=1000, null=True, verbose_name='درباره (انگلیسی)')),
                ('about_persian', models.CharField(blank=True, max_length=1000, null=True, verbose_name='درباره (فارسی)')),
                ('about_arabic', models.CharField(blank=True, max_length=1000, null=True, verbose_name='درباره (عربی)')),
                ('image', models.ImageField(upload_to='images/contatus/', verbose_name='تصویر')),
                ('map_image', models.ImageField(upload_to='images/contatus/map/', verbose_name='تصویر نقشه')),
                ('activate', models.BooleanField(default=False, verbose_name='فعال\u200cسازی')),
            ],
            options={
                'verbose_name': 'لیست تماس با ما',
                'verbose_name_plural': 'لیست\u200cهای تماس با ما',
            },
        ),
    ]
