# Generated by Django 5.1.2 on 2024-11-23 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان (انگلیسی)')),
                ('title_persian', models.CharField(max_length=20, verbose_name='عنوان (فارسی)')),
                ('title_arabic', models.CharField(max_length=20, verbose_name='عنوان (عربی)')),
                ('caption', models.CharField(max_length=128, verbose_name='توضیحات (انگلیسی)')),
                ('caption_persian', models.CharField(max_length=128, verbose_name='توضیحات (فارسی)')),
                ('caption_arabic', models.CharField(max_length=128, verbose_name='توضیحات (عربی)')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف')),
                ('image', models.ImageField(upload_to='image_festival/', verbose_name='تصویر جشنواره')),
                ('activate', models.BooleanField(default=False, verbose_name='فعال\u200cسازی')),
            ],
            options={
                'verbose_name': 'جشنواره فروش',
                'verbose_name_plural': 'جشنواره\u200cهای فروش',
            },
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن (انگلیسی)')),
                ('text_persian', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن (فارسی)')),
                ('text_arabic', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن (عربی)')),
                ('button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='متن دکمه (انگلیسی)')),
                ('button_text_persian', models.CharField(blank=True, max_length=20, null=True, verbose_name='متن دکمه (فارسی)')),
                ('button_text_arabic', models.CharField(blank=True, max_length=20, null=True, verbose_name='متن دکمه (عربی)')),
                ('navigate_to', models.CharField(blank=True, max_length=20, null=True, verbose_name='لینک مسیر')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='site_settings.siteimage', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر',
                'verbose_name_plural': 'تصاویر اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='HomeController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False, verbose_name='فعال\u200cسازی')),
                ('video_trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_controllers', to='site_settings.sitevideo', verbose_name='ویدیو تریلر')),
                ('slider_data', models.ManyToManyField(related_name='home_controllers', to='home.sliderimages', verbose_name='داده\u200cهای اسلایدر')),
            ],
            options={
                'verbose_name': 'کنترلر صفحه اصلی',
                'verbose_name_plural': 'کنترلرهای صفحه اصلی',
            },
        ),
    ]
